from enum import StrEnum

class Reflector(StrEnum):
    UKW = 'QYHOGNECVPUZTFDJAXWMKISRBL'
    ETW = 'QWERTZUIOASDFGHJKPYXCVBNML'
    UKWK = 'IMETCGFRAYSQBZXWLHKDVUPOJN'
    ETWK = 'QWERTZUIOASDFGHJKPYXCVBNML'
    BETA = 'LEYJVCNIXWPBQMDRTAKZGFUHOS'
    GAMMA = 'FSOKANUERHMBTIYCWLQPZXVGJD'
    REFA = 'EJMZALYXVBWFCRQUONTSPIKHGD'
    REFB = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
    REFC = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'
    REFBTHIN = 'ENKQAUYWJICOPBLMDXZVFTHRGS'
    REFCTTHIN = 'RDOBJNTKVEHMLFCWZAXGYIPSUQ'
    REFETW = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

