from enum import StrEnum

class Reflector(StrEnum):
    UKW = 'QYHOGNECVPUZTFDJAXWMKISRBL'
    UKWK = 'IMETCGFRAYSQBZXWLHKDVUPOJN'
    REFA = 'EJMZALYXVBWFCRQUONTSPIKHGD'
    REFB = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
    REFC = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'
    REFBTHIN = 'ENKQAUYWJICOPBLMDXZVFTHRGS'
    REFCTHIN = 'RDOBJNTKVEHMLFCWZAXGYIPSUQ'
    REFETW = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
